--CREATE TABLE DOCTORS(
--ID INT IDENTITY(1,1) NOT NULL,
--DOC_ID AS('DID'+RIGHT('-000000'+CAST(ID AS VARCHAR(7)),7))PERSISTED,
--DOC_NAME VARCHAR(50) NOT NULL,
--DOC_DEPART VARCHAR(50) NOT NULL,
--DOC_TEL VARCHAR(15) NOT NULL UNIQUE,
--DOC_EMAIL VARCHAR(255) NOT NULL UNIQUE,
--DOC_PASS nVARCHAR(50) NOT NULL,
--DOC_GENDER VARCHAR(7) NOT NULL,
--DOC_ADDRESS VARCHAR(100) NOT NULL,
--DOC_DESIG VARCHAR(50) NOT NULL,
--PRIMARY KEY (ID)
--)

--CREATE TABLE PATIENTS(
--ID INT IDENTITY(1,1) NOT NULL,
--PAT_ID AS('PID'+RIGHT('-000000'+CAST(ID AS VARCHAR(7)),7))PERSISTED,
--PAT_NAME VARCHAR(50) NOT NULL,
--PAT_TEL VARCHAR(15) NOT NULL UNIQUE,
--PAT_EMAIL NVARCHAR(255) NOT NULL UNIQUE,
--PAT_PASS NVARCHAR(50) NOT NULL,
--PAT_GENDER VARCHAR(7) NOT NULL,
--PAT_ADDRESS VARCHAR(100) NOT NULL,
--DOC_CODE INT FOREIGN KEY REFERENCES DOCTORS(ID),
--PRIMARY KEY (ID),
--)

--CREATE TABLE DIAGNOSES(
--ID INT IDENTITY(1,1) NOT NULL,
--DIAG_NO AS('DNO'+RIGHT('-000000'+CAST(ID AS VARCHAR(10)),10))PERSISTED,
--DIAG_DETAILS TEXT NOT NULL,
--DIAG_REMARK TEXT NOT NULL,
--DIAG_DATE DATE NOT NULL,
--DIAG_AMOUNT INT NOT NULL,
--DIAG_OTHER TEXT,
--PAT_CODE INT FOREIGN KEY REFERENCES PATIENTS(ID),
--PRIMARY KEY (ID),
--)

--CREATE TABLE BILL(
--ID INT IDENTITY(1,1) NOT NULL,
--BILL_ID AS('BNO'+RIGHT('-000000'+CAST(ID AS VARCHAR(20)),20))PERSISTED,
--PAT_TYPE VARCHAR(50),
--ROOM_CHARGE INT NOT NULL,
--DOC_CHARGE INT NOT NULL,
--OPR_CHARGE INT,
--NURSING_CHARGES INT,
--SERVICE_CHARGE INT,
--STAY_DAYS INT,
--INSURANCE INT,
--HEALTH_CARD VARCHAR(50),
--PAT_CODE INT FOREIGN KEY REFERENCES PATIENTS(ID),
--PRIMARY KEY (ID),
--)

--CREATE TABLE INPATIENT(
--ID INT IDENTITY(1,1) NOT NULL,
--INPAT_ID AS('IPID'+RIGHT('-000000'+CAST(ID AS VARCHAR(10)),10))PERSISTED,
--ROOM_NO VARCHAR(50) NOT NULL,
--DATE_OF_AD DATE NOT NULL,
--DATE_OF_DIS DATE NOT NULL,
--ADVANCE INT,
--DIAG_CODE INT FOREIGN KEY REFERENCES DIAGNOSES(ID),
--PRIMARY KEY (ID),
--)

--CREATE TABLE OUTPATIENT(
--ID INT IDENTITY(1,1) NOT NULL,
--OUTPAT_ID AS('OPID'+RIGHT('-000000'+CAST(ID AS VARCHAR(20)),20))PERSISTED,
--CHECKUP_DATE DATE NOT NULL,
--DIAG_CODE INT FOREIGN KEY REFERENCES DIAGNOSES(ID),
--PRIMARY KEY (ID),
--)

--CREATE TABLE ROOM(
--ID INT IDENTITY(1,1) NOT NULL,
--ROOM_NO VARCHAR(50) NOT NULL,
--ROOM_STATUS VARCHAR(10) NOT NULL,
--ROOM_TYPE VARCHAR(50) NOT NULL,
--INPAT_CODE INT FOREIGN KEY REFERENCES INPATIENT(ID)
--)

----INSERT INTO DOCTORS VALUES('Jamshed','03492896282','jamsheda4ahmed786@gmail.com','12345678','Male','Karachi','Surgeon');

select * from doctors
select * from patients
select * from bill
select * from inpatient
select * from outpatient
select * from room
select * from diagnoses
